
Description: "Custom resource to create a SageMaker notebook. License: (MIT-0: https://github.com/aws/mit-0) (qs-1o9abmj8n)"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required SageMaker Parameters
        Parameters:
          - NotebookInstanceName
          - NotebookInstanceType
          - SageMakerRoleArn
      - Label:
          default: Optional SageMaker Parameters
        Parameters:
          - DirectInternetAccess
          - SageMakerS3BucketForData
          
    ParameterLabels:
      DirectInternetAccess:
        default: Default Internet Access
      NotebookInstanceName:
        default: Notebook Instance Name
      NotebookInstanceType:
        default: Notebook Instance Type
      SageMakerRoleArn:
        default: SageMaker IAM Role
      SageMakerS3BucketForData:
        default: SageMaker S3 Bucket for Data
      SageMakerS3BucketForModelingScripts:
        default: SageMaker S3 Bucket where sample scripts for model exists
Parameters:
  NotebookInstanceName:
    AllowedPattern: '[A-Za-z0-9-]{1,63}'
    ConstraintDescription: Maximum of 63 alphanumeric characters. Can include hyphens
      (-), but not spaces. Must be unique within your account in an AWS Region.
    Description: SageMaker Notebook instance name
    MaxLength: '63'
    MinLength: '1'
    Type: String
  NotebookInstanceType:
    AllowedValues:
      - ml.t2.medium
      - ml.m4.xlarge
      - ml.p2.xlarge
    ConstraintDescription: Must select a valid notebook instance type.
    Default: ml.t2.medium
    Description: Select Instance type for the SageMaker Notebook
    Type: String
  SageMakerRoleArn:
    Description: ARN of the SageMaker IAM execution role. If you don't specify a role, a new role is created with AmazonSageMakerFullAccess managed policy and access is provided to SageMakerS3BucketForData, if provided.
    Type: String
    Default: ''
  SageMakerS3BucketForData:
    Description: Name of a pre-existing bucket that SageMaker will be granted full access
    Type: String
    Default: ''
  DirectInternetAccess:
    Description: Not yet available to custom resource. Sets whether SageMaker notebook instance has internet access. If you set this to Disabled this notebook instance will be able to access resources only in your VPC. This is used only if SubnetId is not empty.
    Type: String
    AllowedValues:
      - Enabled
      - Disabled
    ConstraintDescription: Must select a valid notebook instance type.
    Default: Enabled
Conditions:
  S3BucketEmpty:
    Fn::Equals:
    - ''
    - Ref: SageMakerS3BucketForData
  S3BucketNotEmpty:
    Fn::Not:
    - Condition: S3BucketEmpty
  RoleArnEmpty:
    Fn::Equals:
    - ''
    - Ref: SageMakerRoleArn
  RoleArnNotEmpty:
    Fn::Not:
    - Condition: RoleArnEmpty
Resources:
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref NotebookInstanceType ##"ml.t2.medium"
      RoleArn: 
        Fn::If:
        - RoleArnNotEmpty
        - !Ref SageMakerRoleArn
        - !GetAtt ExecutionRole.Arn   ## !GetAtt ExecutionRole.Arn
      DirectInternetAccess: !Ref DirectInternetAccess
      LifecycleConfigName: !GetAtt BasicNotebookInstanceLifecycleConfig.NotebookInstanceLifecycleConfigName
  BasicNotebookInstanceLifecycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      OnStart:
        - Content:
            Fn::Base64: "echo 'hello'"
  ExecutionRole: 
    Condition: RoleArnEmpty
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      Path: "/service-role/"
      Policies: 
        Fn::If:
        - S3BucketNotEmpty
        - 
          - PolicyName: SageMakerS3BucketAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource:
                    - !Sub 'arn:aws:s3:::${SageMakerS3BucketForData}'
                    - !Sub 'arn:aws:s3:::${SageMakerS3BucketForData}/*'
        - Ref: AWS::NoValue
  NotebookCloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance
  BasicNotebookInstanceLifecycleConfigId:
    Value: !Ref BasicNotebookInstanceLifecycleConfig